// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1_30MYfwSrg8GgOt_ZLD9RJLcX9xaIIM',
    appId: '1:920416438534:web:0a0ffca59b1f5401fdf687',
    messagingSenderId: '920416438534',
    projectId: 'hindustaan-job-new',
    authDomain: 'hindustaan-job-new.firebaseapp.com',
    storageBucket: 'hindustaan-job-new.appspot.com',
    measurementId: 'G-25XZW8C0T3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI_u8Dle6cQQ4U5gxOKyZt60VcVOEKRmU',
    appId: '1:920416438534:android:16ce91bac84a98f9fdf687',
    messagingSenderId: '920416438534',
    projectId: 'hindustaan-job-new',
    storageBucket: 'hindustaan-job-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvDbPfcClOEb3bLCAs3yhde5ymJcI3ndY',
    appId: '1:920416438534:ios:d980a29d4d2d13e0fdf687',
    messagingSenderId: '920416438534',
    projectId: 'hindustaan-job-new',
    storageBucket: 'hindustaan-job-new.appspot.com',
    iosClientId: '920416438534-tf6ar2ia3pbj2lks470bl9vv2hg5lker.apps.googleusercontent.com',
    iosBundleId: 'com.example.hindustanJob',
  );
}
